import { NobarVenue } from '@/types'

export const NOBAR_VENUES: NobarVenue[] = [
  // YOGYAKARTA
  {
    id: 'yk-1',
    name: 'Nobar WC 2026 — Alun-alun Kidul',
    city: 'Yogyakarta',
    address: 'Alun-alun Kidul, Kraton, Yogyakarta',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['LED Screen Besar', 'Food Court', 'Parkir Tersedia', 'Kapasitas 500+'],
    isFree: true,
    openTime: '20:00',
    mapsUrl: 'https://maps.google.com/?q=Alun-alun+Kidul+Yogyakarta',
    phone: undefined,
  },
  {
    id: 'yk-2',
    name: 'Filosofi Kopi Yogyakarta',
    city: 'Yogyakarta',
    address: 'Jl. Ndalem Mangkubumen KT III/578, Yogyakarta',
    type: 'cafe',
    icon: '☕',
    tags: ['AC', 'Proyektor 150"', 'Reservasi Wajib', 'Menu Spesial WC'],
    isFree: false,
    openTime: '21:00',
    mapsUrl: 'https://maps.google.com/?q=Filosofi+Kopi+Yogyakarta',
    phone: '+62 274 123456',
  },
  {
    id: 'yk-3',
    name: 'Angkringan Pak Budi — WC Special',
    city: 'Yogyakarta',
    address: 'Jl. Malioboro No. 45, Yogyakarta',
    type: 'outdoor',
    icon: '🍗',
    tags: ['Outdoor', 'Nasi Kucing', 'Vibe Tradisional', 'Live Bersama Warga'],
    isFree: true,
    openTime: '19:00',
    mapsUrl: 'https://maps.google.com/?q=Malioboro+Yogyakarta',
    phone: undefined,
  },
  {
    id: 'yk-4',
    name: 'Warung Kopi Klotok',
    city: 'Yogyakarta',
    address: 'Jl. Kaliurang KM 16, Sleman, DIY',
    type: 'cafe',
    icon: '🌄',
    tags: ['View Gunung Merapi', 'Outdoor', 'Gratis WiFi', 'Semua Pertandingan'],
    isFree: true,
    openTime: '20:00',
    mapsUrl: 'https://maps.google.com/?q=Warung+Kopi+Klotok+Yogyakarta',
  },
  {
    id: 'yk-5',
    name: 'Timezone Ambarukmo Plaza',
    city: 'Yogyakarta',
    address: 'Ambarukmo Plaza Lt.3, Jl. Laksda Adisucipto, Yogyakarta',
    type: 'mall',
    icon: '🎮',
    tags: ['AC Dingin', 'Indoor', 'Gaming Area', 'Free Snack'],
    isFree: false,
    openTime: '20:30',
    mapsUrl: 'https://maps.google.com/?q=Ambarukmo+Plaza+Yogyakarta',
  },
  {
    id: 'yk-6',
    name: 'Komunitas Bola Jogja (KBJ)',
    city: 'Yogyakarta',
    address: 'Sekretariat KBJ, Jl. Colombo No.1, Yogyakarta',
    type: 'komunitas',
    icon: '⚽',
    tags: ['Komunitas', 'Gratis Member', 'Analisis Live', 'Discord Aktif'],
    isFree: true,
    openTime: '19:30',
    mapsUrl: 'https://maps.google.com/?q=Colombo+Yogyakarta',
  },

  // JAKARTA
  {
    id: 'jkt-1',
    name: 'GBK Fan Zone Senayan',
    city: 'Jakarta',
    address: 'Komplek GBK, Senayan, Jakarta Pusat',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['LED Raksasa', 'Food Festival', 'Kapasitas 5000+', 'Official FIFA Zone'],
    isFree: true,
    openTime: '19:00',
    mapsUrl: 'https://maps.google.com/?q=GBK+Senayan+Jakarta',
  },
  {
    id: 'jkt-2',
    name: 'Kopi Kenangan — WC Corner SCBD',
    city: 'Jakarta',
    address: 'Pacific Place, SCBD, Jakarta Selatan',
    type: 'cafe',
    icon: '☕',
    tags: ['AC', 'Indoor', 'Screen 4K', 'Menu Edisi Khusus WC'],
    isFree: false,
    openTime: '21:00',
    mapsUrl: 'https://maps.google.com/?q=Pacific+Place+Jakarta',
  },

  // SURABAYA
  {
    id: 'sby-1',
    name: 'Nobar WC — Taman Bungkul',
    city: 'Surabaya',
    address: 'Taman Bungkul, Jl. Raya Darmo, Surabaya',
    type: 'outdoor',
    icon: '🌳',
    tags: ['Gratis', 'Outdoor', 'LED Screen', 'Kuliner Sekitar'],
    isFree: true,
    openTime: '20:00',
    mapsUrl: 'https://maps.google.com/?q=Taman+Bungkul+Surabaya',
  },

  // BANDUNG
  {
    id: 'bdg-1',
    name: 'Bandung Super Soccer Hub',
    city: 'Bandung',
    address: 'Jl. Braga No.99, Bandung',
    type: 'cafe',
    icon: '⚽',
    tags: ['Beragam Screen', 'Kapasitas 200', 'Live DJ', 'Menu Lengkap'],
    isFree: false,
    openTime: '20:00',
    mapsUrl: 'https://maps.google.com/?q=Braga+Bandung',
  },

  // MEDAN
  {
    id: 'mdn-1',
    name: 'Lapangan Merdeka WC Zone',
    city: 'Medan',
    address: 'Lapangan Merdeka, Jl. Balai Kota, Medan',
    type: 'outdoor',
    icon: '🏟️',
    tags: ['Gratis', 'LED Outdoor', 'Food Stalls', 'Keluarga'],
    isFree: true,
    openTime: '19:30',
    mapsUrl: 'https://maps.google.com/?q=Lapangan+Merdeka+Medan',
  },

  // MAKASSAR
  {
    id: 'mks-1',
    name: 'Pantai Losari WC Fiesta',
    city: 'Makassar',
    address: 'Anjungan Pantai Losari, Makassar',
    type: 'outdoor',
    icon: '🌊',
    tags: ['View Pantai', 'Gratis', 'Sunset + Bola', 'Kapasitas Besar'],
    isFree: true,
    openTime: '18:00',
    mapsUrl: 'https://maps.google.com/?q=Pantai+Losari+Makassar',
  },

  // SEMARANG
  {
    id: 'smg-1',
    name: 'Kota Lama Nonton Bareng',
    city: 'Semarang',
    address: 'Kawasan Kota Lama, Semarang',
    type: 'outdoor',
    icon: '🏛️',
    tags: ['Heritage Area', 'Gratis', 'Outdoor Romantis', 'Food Stalls'],
    isFree: true,
    openTime: '20:00',
    mapsUrl: 'https://maps.google.com/?q=Kota+Lama+Semarang',
  },
]

export const CITIES = ['Yogyakarta', 'Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Makassar', 'Semarang']
